/**
 * config.js — Central configuration for the Smart Dorm Energy Monitor.
 *
 * API_BASE_URL points to the AWS API Gateway dev stage that fronts
 * four Lambda functions: GetElectricityData, UpdateAlertThreshold,
 * SimulateDeviceData, GetAlertHistory.
 *
 * COGNITO uses the Hosted UI OAuth flow. The App Client must have
 * http://localhost:5173 registered as both an allowed callback URL
 * and an allowed sign-out URL in the AWS Cognito console.
 */

const config = {
  // API Gateway dev-stage base URL (Lambda + DynamoDB backend)
  API_BASE_URL: 'https://n9lxkwwoch.execute-api.ap-southeast-2.amazonaws.com/dev',

  COGNITO: {
    REGION: 'ap-southeast-2',
    USER_POOL_ID: 'ap-southeast-2_DsQ5nNJaA',
    CLIENT_ID: '3p6i821362ls1k0r2n4r3s0f8v',
    // Cognito Hosted UI domain (auto-generated by Cognito)
    DOMAIN: 'ap-southeast-2dsq5nnjaa.auth.ap-southeast-2.amazoncognito.com',
    // Must be registered in App Client > Allowed callback URLs
    REDIRECT_URI: 'http://localhost:5173',
    // Must be registered in App Client > Allowed sign-out URLs
    LOGOUT_URI: 'http://localhost:5173',
    // OIDC scopes requested during authorisation code flow
    SCOPES: 'email openid phone'
  }
};

export default config;
